
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

#
# Configure Using Gemfile
# gem 'pg'
#



development:
  adapter: postgresql
  encoding: unicode
  database: MyDatabase
  host: localhost
  pool: 5
  username: postgres
  password: MyPassword


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: tati
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: MyDatabase_Production
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['MyDatabase_Password'] %>
  role: MyRole

